sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.12.5
addons:
  code_climate:
    repo_token:
      secure: KxQ/EczxnbPPOv42RQnj9nTo7pH0dsNeeODLA+aK5HACMe2DArMQ1q/XLt2I909J2OZMdx0SWwfJF3oKqfD8B5kALovK+A6StTLULhGtWyqeEDdaOgGnxu7eoE5zX4Q7KEq+js5bAjrutTmOflAGGKAyJr6oGnH4pYvGVJKTOV0KGFC41YpSePnIrEy3fXb/qLTGWdBxyskugLFJRZzjoRxmGsr52qEfuNYfIWuGNM2F4wQP3mSpcqsdI/pJIaqx56no8yFC6bB9+1X2Nt0SMkY1OYIzqxjNH/ExCvE5IH4yPJpmdMeBapW7vzwJqqLsZv1YkdXxFtwpsFwai+9Ipxo1CResV1hz46RlkqLKaOYzfj6Eqg6F0p5LPZ6q9HxdzweVZ/nQmXQg0aBDC+4uXTgnb3bh6JWVjjZDWUm45x9UZyJm+gJHz9/TX+4YSeXAL/fPPdC6UwRf2uXUew/D3nFYGGmAErxFKSCHGZEIkPg4NPITiCfESG5mQvfI90h2Z8+IlVlxqkRqo56NL9E26J4F/DaELZGqcoQGwTd38Nr+K3VDCwPgYGzpQwSW4sbcTkffgbLzQRAegt2StzQA4wBykOT5elkDBGX8pZQM2AMdSf592+sNeC3GX5kIy24SJMLRuRa/kxCs3vPeEwyrFQbm5G+3Dn4lmvw6HTrOshg=
